version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: nest_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestor_academico
      MYSQL_USER: adminuni
      MYSQL_PASSWORD: contrauni
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 5s

  backend:
    build: .
    container_name: nest_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy  
    env_file:
      - .env

volumes:
  mysql_data:
